### ISSUE TITLE
PWA101(v2.0): rewrite PWA101 tutorial in SymPy

### ISSUE THREAD

**Issue by shenvitor** [ComPWA/gluex-nstar#1]
Previous version of PWA101 (v1.0) see [here](https://github.com/ComPWA/compwa.github.io/pull/217)
In these tasks, we have the following.
Furthermore:

```[tasklist]
### Original Tasks
- [ ] https://github.com/ComPWA/gluex-nstar/issues/5
- [ ] https://github.com/ComPWA/gluex-nstar/issues/2
- [ ] https://github.com/ComPWA/gluex-nstar/pull/13
- [ ] https://github.com/ComPWA/gluex-nstar/issues/36
- [ ] https://github.com/ComPWA/gluex-nstar/issues/3
```

```[tasklist]
### Up-to-date Tasks
- [x] pgamma virtual state particle and QRules
- [x] symbolics expression of amplitude A from the examples
```
