### ISSUE TITLE
Make model plots interactive with `ipywidgets` sliders

### ISSUE THREAD

**Issue by shenvitor** [ComPWA/gluex-nstar#31]
Make the model visualisations from #13, #28, and #29 interactive with [`ipywidgets`](https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html).

For some examples of how to use `ipywidgets` see ~[this search result](https://compwa.github.io/search.html?q=ipywidgets) on the ComPWA website~ the examples on the [`ampform-dpd` website](https://compwa.github.io/ampform-dpd), e.g. [this one](https://compwa.github.io/ampform-dpd/comparison/d2kkk.html)). The examples only show the main idea of `ipywidgets` plus plotting; some translation will have to be done for what how we want to visualise the models exactly.

There are three types of widgets+matplotlib cells that need to be implemented:
1. 1D histogram
2. 2D histogram
3. Line plots (e.g. Argand and BW lineshape plots)

**Best to start with the notebook that was implemented in #17** ($p\gamma \to p \pi^0 \eta$: the model has the smallest number of parameters and it only contains 1D histograms.
```[tasklist]
### Related PRs
- [ ] https://github.com/ComPWA/gluex-nstar/pull/13
- [ ] https://github.com/ComPWA/gluex-nstar/pull/28
- [ ] https://github.com/ComPWA/gluex-nstar/pull/29
- [ ] https://github.com/ComPWA/gluex-nstar/pull/56
- [ ] https://github.com/ComPWA/gluex-nstar/issues/67
- [ ] https://github.com/ComPWA/gluex-nstar/issues/72
- [ ] https://github.com/ComPWA/gluex-nstar/issues/74
```
