### ISSUE TITLE
Generate phase space and visualize model over all kinematic variables

### ISSUE THREAD

**Issue by shenvitor** [ComPWA/gluex-nstar#61]
```[tasklist]
### Tasks
- [x] Generate phase space sample with TensorWaves
- [ ] Write symbolic momentum-to-angle/Mandelstam `dict` (see [here](https://ampform.readthedocs.io/0.15.x/usage/kinematics.html) for symbolic boosts)
- [ ] https://github.com/ComPWA/gluex-nstar/issues/36
- [ ] Insert kinematic variables into model with [`SympyDataTransformer`](https://tensorwaves.readthedocs.io/0.4.x/api/tensorwaves.data.transform/#tensorwaves.data.transform.SympyDataTransformer)
```

**Comment by shenvitor** [comment]
[RotationYMatrix](https://ampform.readthedocs.io/0.15.x/api/ampform.kinematics.lorentz.html#ampform.kinematics.lorentz.RotationYMatrix)
[RotationZMatrix](https://ampform.readthedocs.io/0.15.x/api/ampform.kinematics.lorentz.html#ampform.kinematics.lorentz.RotationZMatrix)
