### ISSUE TITLE
Add sliders for amplitude coefficients (weight and phase)

### ISSUE THREAD

**Issue by redeboer** [ComPWA/gluex-nstar#74]
```[tasklist]
### Tasks
- [x] Reorganize UI into nested tabs for resonances
- [x] Create sliders for C and phi
- [x] Recombine C and phi `parameters` numerically into complex value
- [x] Update plots (probably already works after new UI design)
```
