### ISSUE TITLE
Improve website interface

### ISSUE THREAD

**Issue by redeboer** [ComPWA/gluex-nstar#76]
```[tasklist]
### Tasks
- [x] Reflect `docs/` folder structure on page structure on the website using [`toctree`](https://myst-parser.readthedocs.io/en/stable/syntax/organising_content.html#using-toctree-to-include-other-documents-as-children)
- [x] Add button with [link to GitHub repo](https://sphinx-book-theme.readthedocs.io/en/stable/components/source-files.html#add-a-link-to-your-repository)
- [x] Change download buttons to [links to source code](https://sphinx-book-theme.readthedocs.io/en/stable/components/source-files.html#add-a-button-to-the-page-source)
- [x] Add button to [suggest edits](https://sphinx-book-theme.readthedocs.io/en/stable/components/source-files.html#add-a-button-to-suggest-edits) and [issues](https://sphinx-book-theme.readthedocs.io/en/stable/components/source-files.html#add-a-button-to-open-issues)
- [x] Add "under active development" [banner](https://sphinx-book-theme.readthedocs.io/en/stable/sections/announcements.html#announcement-banners)
- [x] Add [interactivity buttons](https://sphinx-book-theme.readthedocs.io/en/stable/content/launch.html)
- [x] Add [favicon](https://github.com/ComPWA/policy/blob/0d7784c8624cb103e720ba4eafe19446260eee03/docs/conf.py#L63) (see [this one](https://github.com/ComPWA/policy/blob/69aa3b419c300639ac3ee6c4e0d7f451f1576e90/docs/_static/favicon.ico)).
- [x] Add [GlueX logo](https://github.com/user-attachments/assets/5650480b-8bed-4fb2-9f2b-c43b12e16ac3) or ComPWA logo in sidebar
- [x] ~[Optional] Switch to [`sphinx-external-toc`](https://sphinx-external-toc.rtfd.io)~
```

See [here](https://github.com/ComPWA/policy/blob/0d7784c8624cb103e720ba4eafe19446260eee03/docs/conf.py#L74-L99) for inspiration.

**Comment by redeboer** [comment]
This issue is best done before #60, so that we can have an `ampform-dpd/` directory next to the existing `ampform/` directory

**Comment by redeboer** [comment]
@shenvitor, in Sphinx documents, you usually organise content with [`toctree`](https://myst-parser.readthedocs.io/en/stable/syntax/organising_content.html#using-toctree-to-include-other-documents-as-children). I would try that first. Later on, we may try to organise with [`sphinx-external-toc`](https://sphinx-external-toc.rtfd.io/) as well.

**Comment by redeboer** [comment]
Suggested structure:

```pip-requirements
index.md
branching-fractions.md
LambdaKpi.md  # new
LambdaKpi/
    ampform.ipynb
    ampform-dpd.ipynb
    manual.ipynb
etapip.md  # reaction.md
etapip/
    ampform.ipynb
    manual.ipynb
```

**Comment by shenvitor** [comment]
> Suggested structure:
> 
> ```pip-requirements
> index.md  # <-- main toctree
> branching-fractions.md
> LambdaKpi.md  # <-- sub toctree, NEW
> LambdaKpi/
>     ampform.ipynb
>     ampform-dpd.ipynb  # next PR!
>     manual.ipynb
> etapip.md  # <-- sub toctree, originally reaction.md
> etapip/
>     ampform.ipynb
>     manual.ipynb
> ```



index.md  # <-- main toctree
branching-fractions.md
~~LambdaKpi.md  # <-- sub toctree, NEW~~
lambda-k-pi/
    index.md  # <-- sub toctree, NEW
    ampform.ipynb
    ampform-dpd.ipynb  # next PR!
    manual.ipynb
~~etapip.md  # <-- sub toctree, originally reaction.md~~
eta-pi-p/
    index.md  # <-- sub toctree, originally reaction.md
    ampform.ipynb
    manual.ipynb

**Comment by redeboer** [comment]
```pip-requirements
index.md  # <-- main toctree
branching-fractions.md
lambda-k-pi/
    index.md  # <-- sub toctree, NEW
    automatic.ipynb
    manual.ipynb
eta-pi-p/
    index.md  # <-- sub toctree, originally reaction.md
    automatic.ipynb
    manual.ipynb
```

**Comment by redeboer** [comment]
Btw, you can later on set [redirects](https://docs.readthedocs.io/en/stable/user-defined-redirects.html) on your Read the Docs page ([gluex-nstar.rtfd.io](https://gluex-nstar.readthedocs.io)).

**Comment by redeboer** [comment]
For the banner, see e.g. here:
https://github.com/ComPWA/polarimetry/blob/83d1c3fb0b55ef27504cd1db700b9c09a0f22640/docs/conf.py#L292-L297
